// This file is auto-generated by `scripts/import-listings.mjs`.
// DO NOT EDIT THIS FILE MANUALLY.
// Run `npm run import-listings` to regenerate.

import { Product } from './types';

export const GENERATED_PRODUCTS: Product[] = [];
